### ISSUE TITLE
A few META issues

### ISSUE THREAD

**Issue by pghmcfc** [coppit/filehandle-unget#1]
As you seem to be active again on CPAN, here's a few items I spotted in the recent release of FileHandle-Unget:

 1. The META.yml file specifies the version as 0.15 rather than 0.1624
 2. The LICENSE file shipped in the distribution includes the old address for the Free Software Foundation; you can get an updated copy with the new address from http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt (this also affects Mail-Mbox-MessageParser)
 3. You don't appear to specify any particular version of the GPL for the license, which is generally interpreted as "choose any version you want"; is that intentional?
 4. The CPAN META spec now incorporates fields for things like repository URL and bug tracker; adding these to your META.yml would mean that MetaCPAN.org's entry for your dist would include links to your repo on github, though you might need to use different tooling to create this.

Thanks for the updates.

**Comment by coppit** [comment]
Thanks a ton for the feedback. I thought the META.yml would be regenerated,
but I see that it's only regenerated if it's missing. I hope I'm not
supposed to maintain it by hand. Updating things like the version would be
annoying, although I suppose I could automate it in Makefile.PL.

I'll update the LICENSE file.

I would expect that the actual license included in the distro would be the
version that would apply. Why else would I include it?

Thanks for the META tips. I saw that it changed significantly since my last
release, but didn't look carefully. I'll need to read up on the (now 3)
different META files.

**Comment by coppit** [comment]
I looked more into your points #3 and #4. Module::Install doesn't support
the CPAN::Meta 2.0 spec yet, which is required for both, and which I'm
using to generate the META.yml file.

Before taking on the manual maintenance of META.yml (or META.json), I'd
like to wait a bit and see if Module::Install will update to support the
2.0 spec.

In the meantime, I've noted these suggestions in my TODO.

**Comment by pghmcfc** [comment]
I saw a related blog post today, which might be useful:
http://neilb.org/2015/04/05/github-repo-module-install.html

**Comment by coppit** [comment]
Thanks. I've incorporated that, as well as several other nifty Module::Install tricks I didn't know about. (Automatic LICENSE file generation, automatic rt.cpan.org bug tracker.) Speaking of rt.cpan.org, I'm moving bug/rfe tracking to there, FYI. https://rt.cpan.org/Public/Dist/Display.html?Name=FileHandle-Unget
